package main

import (
	"crypto/sha256"
	"encoding/hex"
	"log"
	"net/http"
	"os"
	"path/filepath"
	"runtime"

	docsapp "github.com/odvcencio/gotreesitter-docs/app"
	_ "github.com/odvcencio/gotreesitter-docs/modules"
	"m31labs.dev/gosx"
	"m31labs.dev/gosx/env"
	islandprogram "m31labs.dev/gosx/island/program"
	"m31labs.dev/gosx/route"
	"m31labs.dev/gosx/server"
)

func main() {
	_, thisFile, _, _ := runtime.Caller(0)
	root := server.ResolveAppRoot(thisFile)
	if err := env.LoadDir(root, ""); err != nil {
		log.Fatal(err)
	}
	docsapp.BindPublicAssetURL(func(path string) string {
		return versionedPublicAssetURL(root, path)
	})
	port := getenv("PORT", "8080")

	router := route.NewRouter()
	router.SetLayout(func(ctx *route.RouteContext, body gosx.Node) gosx.Node {
		ctx.AddHead(server.NavigationScript())
		// Space Grotesk + JetBrains Mono are the current site's two typefaces.
		// This is the
		// site's actual head (app/layout.gsx only renders the body shell), so
		// the fonts are wired in here rather than in the .gsx layout.
		ctx.AddHead(
			gosx.El("link", gosx.Attrs(gosx.Attr("rel", "preconnect"), gosx.Attr("href", "https://fonts.googleapis.com"))),
			gosx.El("link", gosx.Attrs(gosx.Attr("rel", "preconnect"), gosx.Attr("href", "https://fonts.gstatic.com"), gosx.BoolAttr("crossorigin"))),
			server.Stylesheet("https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@400;500;600;700&family=JetBrains+Mono:ital,wght@0,400;0,500;0,700;1,400&display=swap"),
		)
		ctx.AddHead(server.Stylesheet(docsapp.PublicAssetURL("docs.css")))
		ctx.AddHead(gosx.El("link", gosx.Attrs(
			gosx.Attr("rel", "icon"),
			gosx.Attr("type", "image/svg+xml"),
			gosx.Attr("href", docsapp.PublicAssetURL("favicon.svg")),
		)))
		return server.HTMLDocument(ctx.Title("GoTreeSitter Docs"), ctx.Head(), body)
	})

	if err := router.AddDir(filepath.Join(root, "app"), route.FileRoutesOptions{}); err != nil {
		log.Fatal(err)
	}

	app := server.New()
	router.SetRevalidator(app.Revalidator())
	app.EnableISR()
	app.EnableNavigation()
	app.SetPublicDir(filepath.Join(root, "public"))
	// A `gosx build` run stages the real WASM runtime + bootstrap JS the
	// islands need to hydrate into dist/ (build.json + assets/runtime/*);
	// without this, /gosx/wasm_exec.js and /gosx/runtime.wasm 404 and every
	// island stays server-HTML-only. dist/ is build output (gitignored,
	// regenerated by CI/deploy — see .gitignore), so this only takes effect
	// once that build has actually run; plain `go run .` in dev still falls
	// back to server's no-op bootstrap stub exactly as before.
	if info, err := os.Stat(filepath.Join(root, "dist", "build.json")); err == nil && !info.IsDir() {
		app.SetRuntimeRoot(filepath.Join(root, "dist"))
	}
	mountIslandProgram(
		app,
		docsapp.LangSearchProgramPath,
		docsapp.LangSearchProgram(),
		docsapp.LangSearchProgramContentVersion(),
	)
	app.Redirect("GET /docs", "/docs/introduction", http.StatusTemporaryRedirect)
	app.API("GET /healthz", func(ctx *server.Context) (any, error) {
		ctx.NoStore()
		return map[string]any{
			"ok":      true,
			"product": "gotreesitter-docs",
			"version": docsapp.PlaygroundGTSVersion(),
		}, nil
	})
	rootHandler, err := router.BuildChecked()
	if err != nil {
		log.Fatal(err)
	}
	app.Mount("/", rootHandler)

	log.Printf("gotreesitter-docs at http://localhost:%s", port)
	log.Fatal(app.ListenAndServe(":" + port))
}

// mountIslandProgram serves a compiled island program's opcode JSON at
// path, matching the pattern GoSX's own examples use (examples/counter,
// examples/hotswap): the client bootstrap fetches this once (prefetched via
// island.Renderer.PreloadHints) and interprets it in the shared WASM VM.
// app/lang_island.go's SetProgramAsset call points at this path.
func mountIslandProgram(app *server.App, path string, prog *islandprogram.Program, contentVersion string) {
	data, err := islandprogram.EncodeJSON(prog)
	if err != nil {
		log.Fatalf("gotreesitter-docs: encode island program %s: %v", path, err)
	}
	app.Mount(path, http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		if contentVersion != "" && r.URL.Query().Get("v") == contentVersion {
			w.Header().Set("Cache-Control", "public, max-age=31536000, immutable")
		} else {
			w.Header().Set("Cache-Control", "public, max-age=0, must-revalidate")
		}
		_, _ = w.Write(data)
	}))
}

func getenv(key, fallback string) string {
	if value := os.Getenv(key); value != "" {
		return value
	}
	return fallback
}

func versionedPublicAssetURL(root, name string) string {
	base := server.AssetURL(name)
	payload, err := os.ReadFile(filepath.Join(root, "public", filepath.FromSlash(name)))
	if err != nil {
		return base
	}
	sum := sha256.Sum256(payload)
	return base + "?v=" + hex.EncodeToString(sum[:6])
}
