package main

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"log"
	"net/http"
	"os"
	"path/filepath"
	"runtime"

	"github.com/andybalholm/brotli"
	docsapp "github.com/odvcencio/gotreesitter-docs/app"
	_ "github.com/odvcencio/gotreesitter-docs/modules"
	"m31labs.dev/gosx"
	runtimehost "m31labs.dev/gosx/client/runtime/host"
	"m31labs.dev/gosx/env"
	islandprogram "m31labs.dev/gosx/island/program"
	"m31labs.dev/gosx/route"
	"m31labs.dev/gosx/server"
)

func main() {
	_, thisFile, _, _ := runtime.Caller(0)
	root := server.ResolveAppRoot(thisFile)
	if err := env.LoadDir(root, ""); err != nil {
		log.Fatal(err)
	}
	docsapp.BindPublicAssetURL(func(path string) string {
		return versionedPublicAssetURL(root, path)
	})
	port := getenv("PORT", "8080")

	router := route.NewRouter()
	router.SetNavigationHead(deferredNavigationHead)
	router.SetLayout(func(ctx *route.RouteContext, body gosx.Node) gosx.Node {
		ctx.AddHead(
			server.Font(server.FontProps{
				Family:  "Space Grotesk",
				Src:     docsapp.PublicAssetURL("fonts/space-grotesk-latin.woff2"),
				Type:    "font/woff2",
				Format:  "woff2",
				Weight:  "400 700",
				Display: "optional",
			}),
			server.Font(server.FontProps{
				Family:  "JetBrains Mono",
				Src:     docsapp.PublicAssetURL("fonts/jetbrains-mono-latin.woff2"),
				Type:    "font/woff2",
				Format:  "woff2",
				Weight:  "400 700",
				Display: "optional",
			}),
			server.Font(server.FontProps{
				Family:    "JetBrains Mono",
				Src:       docsapp.PublicAssetURL("fonts/jetbrains-mono-latin-italic.woff2"),
				Type:      "font/woff2",
				Format:    "woff2",
				Weight:    "400",
				Style:     "italic",
				Display:   "optional",
				NoPreload: true,
			}),
		)
		ctx.AddHead(server.Stylesheet(docsapp.PublicAssetURL("docs.css")))
		ctx.AddHead(gosx.El("link", gosx.Attrs(
			gosx.Attr("rel", "icon"),
			gosx.Attr("type", "image/svg+xml"),
			gosx.Attr("href", docsapp.PublicAssetURL("favicon.svg")),
		)))
		// Cloudflare Web Analytics (RUM) — cookieless, privacy-friendly beacon.
		// Loaded from the site head; the module script defers automatically.
		ctx.AddHead(gosx.El("script", gosx.Attrs(
			gosx.Attr("type", "module"),
			gosx.Attr("src", "https://static.cloudflareinsights.com/beacon.min.js"),
			gosx.Attr("data-cf-beacon", `{"token": "0282fc84c88d4a37820b398987f22b2d"}`),
		)))
		ctx.SetLanguage("en")
		return server.HTMLDocument(ctx.Document("gotreesitter", body))
	})

	if err := router.AddDir(filepath.Join(root, "app"), route.FileRoutesOptions{}); err != nil {
		log.Fatal(err)
	}

	app := server.New()
	app.Use(playgroundWASMCompression(root))
	app.Mount(navigationRuntimeAssetURL(), navigationRuntimeAssetHandler())
	router.SetRevalidator(app.Revalidator())
	app.EnableISR()
	app.SetPublicDir(filepath.Join(root, "public"))
	// A `gosx build` run stages the real WASM runtime + bootstrap JS the
	// islands need to hydrate into dist/ (build.json + assets/runtime/*);
	// without this, /gosx/wasm_exec.js and /gosx/runtime.wasm 404 and every
	// island stays server-HTML-only. dist/ is build output (gitignored,
	// regenerated by CI/deploy — see .gitignore), so this only takes effect
	// once that build has actually run; plain `go run .` in dev still falls
	// back to server's no-op bootstrap stub exactly as before.
	if info, err := os.Stat(filepath.Join(root, "dist", "build.json")); err == nil && !info.IsDir() {
		app.SetRuntimeRoot(filepath.Join(root, "dist"))
	}
	mountIslandProgram(
		app,
		docsapp.LangSearchProgramPath,
		docsapp.LangSearchProgram(),
		docsapp.LangSearchProgramContentVersion(),
	)
	app.Redirect("GET /docs", "/docs/introduction", http.StatusTemporaryRedirect)
	app.API("GET /healthz", func(ctx *server.Context) (any, error) {
		ctx.NoStore()
		return map[string]any{
			"ok":      true,
			"product": "gotreesitter-docs",
			"version": docsapp.PlaygroundGTSVersion(),
		}, nil
	})
	rootHandler, err := router.BuildChecked()
	if err != nil {
		log.Fatal(err)
	}
	app.Mount("/", rootHandler)

	log.Printf("gotreesitter-docs at http://localhost:%s", port)
	log.Fatal(app.ListenAndServe(":" + port))
}

// deferredNavigationHead references GoSX's own managed-navigation runtime as
// a deferred, cacheable module asset so its source does not sit inline in every
// server-rendered page.
func deferredNavigationHead(nonce string) gosx.Node {
	attrs := []any{
		gosx.BoolAttr("defer"),
		gosx.Attr("data-gosx-navigation", "true"),
		gosx.Attr("fetchpriority", "low"),
		gosx.Attr("src", navigationRuntimeAssetURL()),
	}
	if nonce != "" {
		attrs = append(attrs, gosx.Attr("nonce", nonce))
	}
	return gosx.El("script", gosx.Attrs(attrs...))
}

func navigationRuntimeAssetURL() string {
	sum := sha256.Sum256([]byte(runtimehost.NavigationRuntime))
	return fmt.Sprintf("/_app/runtime/navigation.%x.js", sum[:6])
}

func navigationRuntimeAssetHandler() http.Handler {
	source := []byte(runtimehost.NavigationRuntime)
	var compressed bytes.Buffer
	writer := brotli.NewWriterLevel(&compressed, brotli.BestCompression)
	if _, err := writer.Write(source); err != nil {
		panic(fmt.Errorf("compress GoSX navigation runtime: %w", err))
	}
	if err := writer.Close(); err != nil {
		panic(fmt.Errorf("finish GoSX navigation runtime compression: %w", err))
	}
	br := compressed.Bytes()
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodGet && r.Method != http.MethodHead {
			http.Error(w, http.StatusText(http.StatusMethodNotAllowed), http.StatusMethodNotAllowed)
			return
		}
		w.Header().Set("Content-Type", "text/javascript; charset=utf-8")
		w.Header().Set("Cache-Control", "public, max-age=31536000, immutable")
		w.Header().Add("Vary", "Accept-Encoding")
		payload := source
		if acceptsBrotli(r.Header.Get("Accept-Encoding")) {
			w.Header().Set("Content-Encoding", "br")
			payload = br
		}
		w.Header().Set("Content-Length", fmt.Sprint(len(payload)))
		if r.Method == http.MethodGet {
			_, _ = w.Write(payload)
		}
	})
}

// mountIslandProgram serves a compiled island program's opcode JSON at
// path, matching the pattern GoSX's own examples use (examples/counter,
// examples/hotswap): the client bootstrap fetches this once (prefetched via
// island.Renderer.PreloadHints) and interprets it in the shared WASM VM.
// app/lang_island.go's SetProgramAsset call points at this path.
func mountIslandProgram(app *server.App, path string, prog *islandprogram.Program, contentVersion string) {
	data, err := islandprogram.EncodeJSON(prog)
	if err != nil {
		log.Fatalf("gotreesitter-docs: encode island program %s: %v", path, err)
	}
	app.Mount(path, http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		if contentVersion != "" && r.URL.Query().Get("v") == contentVersion {
			w.Header().Set("Cache-Control", "public, max-age=31536000, immutable")
		} else {
			w.Header().Set("Cache-Control", "public, max-age=0, must-revalidate")
		}
		_, _ = w.Write(data)
	}))
}

func getenv(key, fallback string) string {
	if value := os.Getenv(key); value != "" {
		return value
	}
	return fallback
}

func versionedPublicAssetURL(root, name string) string {
	base := server.AssetURL(name)
	payload, err := os.ReadFile(filepath.Join(root, "public", filepath.FromSlash(name)))
	if err != nil {
		return base
	}
	sum := sha256.Sum256(payload)
	return base + "?v=" + hex.EncodeToString(sum[:6])
}
