// Command build-authoring-wasm produces the browser-only grammar-authoring
// engine consumed by the GoSX authoring surface (app/authoring). Unlike
// build-playground-wasm, it ships no pre-generated grammar blobs: grammargen
// compiles the user's grammar.json live, in the browser, so the only outputs
// are wasm binaries (plus, for the worker, a small generated JS bootstrap —
// see workerBootstrapJS below for why that's generated here rather than
// hand-authored and checked in).
//
// Phase 1 builds two wasm binaries:
//   - authoring.wasm: the GoSX island (cmd/authoring-wasm) that owns the DOM
//     — unchanged in shape from Phase 0.
//   - authoring-worker.wasm: a plain (non-GoSX) js/wasm build
//     (cmd/authoring-worker-wasm) that runs the actual grammargen
//     compile+parse+diagnose+highlight loop inside a Web Worker, off the
//     main thread, so a heavy grammar cannot freeze the tab. It is loaded by
//     authoring-worker.js, a small generated bootstrap (importScripts the
//     already-served /gosx/standard-go-wasm_exec.js Go/wasm shim, then
//     fetch+instantiate+run authoring-worker.wasm) — mechanical Go/wasm
//     boilerplate, not application logic, so it is generated at build time
//     into public/authoring/ and gitignored, exactly like the wasm binaries
//     themselves. This keeps the repository's "no hand-authored JS" rule
//     (see scripts/verify-production.sh) intact: every byte of behavior is
//     still authored in Go.
package main

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
)

func main() {
	root, err := repositoryRoot()
	if err != nil {
		fatal(err)
	}
	outDir := filepath.Join(root, "public", "authoring")
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		fatal(err)
	}

	buildWASM(root, filepath.Join(outDir, "authoring.wasm"), "./cmd/authoring-wasm")
	buildWASM(root, filepath.Join(outDir, "authoring-worker.wasm"), "./cmd/authoring-worker-wasm")
	writeWorkerBootstrap(filepath.Join(outDir, "authoring-worker.js"), filepath.Join(outDir, "authoring-worker.wasm"))
}

func buildWASM(root, output, pkg string) {
	command := exec.Command(
		"go", "build",
		"-trimpath",
		"-ldflags=-s -w",
		"-o", output,
		pkg,
	)
	command.Dir = root
	command.Env = append(os.Environ(), "GOWORK=off", "GOOS=js", "GOARCH=wasm")
	command.Stdout = os.Stdout
	command.Stderr = os.Stderr
	if err := command.Run(); err != nil {
		fatal(err)
	}
	info, err := os.Stat(output)
	if err != nil {
		fatal(err)
	}
	fmt.Printf("built %s (%d bytes)\n", output, info.Size())
}

// writeWorkerBootstrap generates the Worker's entry script. A Worker always
// needs a JS entry point (there is no way to start one with pure wasm — the
// Worker constructor requires a script URL, and Go's wasm output needs the
// host bindings wasm_exec.js provides), so this is unavoidable, but it is
// intentionally minimal: importScripts the standard Go wasm_exec.js the
// framework already serves for every "go-wasm" runtime engine on this page
// (/gosx/standard-go-wasm_exec.js — see main_stub reference in
// cmd/authoring-wasm), then fetch+instantiate+run authoring-worker.wasm
// (resolved relative to this script's own URL so it survives any future
// path/versioning changes). All actual behavior — the compile loop, the
// message protocol, diagnostics, highlighting — lives in
// cmd/authoring-worker-wasm's Go source, not here.
func writeWorkerBootstrap(scriptPath, wasmPath string) {
	sum, err := fileSHA256Prefix(wasmPath)
	if err != nil {
		fatal(err)
	}
	script := "// GENERATED by cmd/build-authoring-wasm — do not hand-edit.\n" +
		"// wasm=" + sum + "\n" +
		workerBootstrapJS
	if err := os.WriteFile(scriptPath, []byte(script), 0o644); err != nil {
		fatal(err)
	}
	info, err := os.Stat(scriptPath)
	if err != nil {
		fatal(err)
	}
	fmt.Printf("built %s (%d bytes)\n", scriptPath, info.Size())
}

const workerBootstrapJS = `(function () {
  "use strict";
  try {
    self.importScripts("/gosx/standard-go-wasm_exec.js");
  } catch (err) {
    self.postMessage({ seq: -1, generateError: "authoring worker: failed to load the Go wasm runtime: " + err });
    return;
  }
  var GoCtor = self.__gosx_standard_go_wasm_ctor || self.Go;
  if (typeof GoCtor !== "function") {
    self.postMessage({ seq: -1, generateError: "authoring worker: standard Go wasm runtime unavailable" });
    return;
  }
  var go = new GoCtor();
  var wasmURL = new URL("authoring-worker.wasm", self.location.href).href;
  fetch(wasmURL)
    .then(function (resp) {
      if (!resp.ok) {
        throw new Error("fetch " + wasmURL + ": " + resp.status);
      }
      return resp.arrayBuffer();
    })
    .then(function (bytes) {
      return WebAssembly.instantiate(bytes, go.importObject);
    })
    .then(function (result) {
      go.run(result.instance);
    })
    .catch(function (err) {
      self.postMessage({ seq: -1, generateError: "authoring worker failed to start: " + err });
    });
})();
`

func fileSHA256Prefix(path string) (string, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return "", err
	}
	sum := sha256.Sum256(data)
	return hex.EncodeToString(sum[:6]), nil
}

func repositoryRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if info, statErr := os.Stat(filepath.Join(dir, "go.mod")); statErr == nil && !info.IsDir() {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("cannot find repository go.mod")
		}
		dir = parent
	}
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, "build-authoring-wasm:", err)
	os.Exit(1)
}
